# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb4f9e6830ac02cfeff75b2ce170509b71b74153c15cb42ad6eb9c086c4e434411b9837f51336ce125a299276f2629364e34f9b6ffee51e33c3755ec88c0c1d9

test:
  secret_key_base: 1c3c83cd06a2a90e981e36896e4d9b59a8bc2a24ba70f1e6febfea19b5cc4e8a226bea0b8fef2b51a3e719e59bf62e1b67097070b31ba8e7fc6657a8a94ea403

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
